version: 0.2
env:
  variables:
    PRX_LAMBDA_CODE_CONFIG_PARAMETERS: "RadiotopiaTowerLambdaCodeS3ObjectKey"
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "docker build ."
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
