FROM alpine:latest

LABEL maintainer="PRX <sysadmin@prx.org>"
LABEL org.prx.spire.publish.s3="LAMBDA_LAYER_ZIP"

WORKDIR /app

RUN mkdir --parents ./nodejs
RUN mkdir --parents /.prxci

RUN apk add zip

RUN npm install --global npm@latest
RUN npm install --prefix ./nodejs @rgrove/parse-xml

# This zip file is what will be deployed as the Lambda layer.
# Add any necessary files to it.
RUN zip --quiet --recurse-paths /.prxci/build.zip ./nodejs
